### ISSUE TITLE
it's possible to use on mac

### ISSUE THREAD

**Issue by Jovisx** [pepeizq/City-Builder#1]
I'm trying to run the app on Mac, but I receive only a strange screen, I would like to help to create the app for mac too but is impossibile.
Thanks

**Comment by pepeizq** [comment]
I have in mind to support Mac and Linux, but first I still have a lot of work to have a game that is worth playing.

Unfortunately I can not give dates why I develop this game in my free time.

**Comment by Jovisx** [comment]
Nice to hear that,
if you need help contact me on email, I think one is here on Github somewhere.
I'd like to help you in creating the game
